/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type Content = Array<
  | ({
      _key: string
    } & TextHeaderSection)
  | ({
      _key: string
    } & ImageHeaderSection)
  | ({
      _key: string
    } & TextSection)
  | ({
      _key: string
    } & CtaBannerSection)
  | ({
      _key: string
    } & FurtherLinkSection)
  | ({
      _key: string
    } & AccordionSection)
  | ({
      _key: string
    } & TestimonialSection)
  | ({
      _key: string
    } & NewsSection)
>

export type NewsSection = {
  _type: 'newsSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
          | 'small'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              type: 'external' | 'internal'
              href?: string
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              _type: 'link'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'publication'
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'news'
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        altText: string
        promptForImage?: string
        _type: 'imageBlock'
        _key: string
      }
    | {
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        _type: 'buttons'
        _key: string
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
  >
  loadAll?: boolean
  news?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'news'
  }>
}

export type FurtherLinkSection = {
  _type: 'furtherLinkSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
          | 'small'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              type: 'external' | 'internal'
              href?: string
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              _type: 'link'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'publication'
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'news'
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        altText: string
        promptForImage?: string
        _type: 'imageBlock'
        _key: string
      }
    | {
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        _type: 'buttons'
        _key: string
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
  >
  links: Array<
    {
      _key: string
    } & LinkCard
  >
}

export type CtaBannerSection = {
  _type: 'ctaBannerSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
          | 'small'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              type: 'external' | 'internal'
              href?: string
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              _type: 'link'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'publication'
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'news'
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        altText: string
        promptForImage?: string
        _type: 'imageBlock'
        _key: string
      }
    | {
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        _type: 'buttons'
        _key: string
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
  >
}

export type TextSection = {
  _type: 'textSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  subtitle?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
          | 'small'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              type: 'external' | 'internal'
              href?: string
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              _type: 'link'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'publication'
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'news'
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        altText: string
        promptForImage?: string
        _type: 'imageBlock'
        _key: string
      }
    | {
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        _type: 'buttons'
        _key: string
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
  >
}

export type TestimonialSection = {
  _type: 'testimonialSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
          | 'small'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              type: 'external' | 'internal'
              href?: string
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              _type: 'link'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'publication'
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'news'
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        altText: string
        promptForImage?: string
        _type: 'imageBlock'
        _key: string
      }
    | {
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        _type: 'buttons'
        _key: string
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
  >
  loadTags?: Array<string>
  testimonials?: Array<{
    _ref: string
    _type: 'reference'
    _weak?: boolean
    _key: string
    [internalGroqTypeReferenceTo]?: 'testimonial'
  }>
}

export type AccordionSection = {
  _type: 'accordionSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
          | 'small'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              type: 'external' | 'internal'
              href?: string
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              _type: 'link'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'publication'
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'news'
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        altText: string
        promptForImage?: string
        _type: 'imageBlock'
        _key: string
      }
    | {
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        _type: 'buttons'
        _key: string
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
  >
  accordion: Array<
    {
      _key: string
    } & AccordionItem
  >
}

export type ImageHeaderSection = {
  _type: 'imageHeaderSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  subtitle?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  image: {
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText: string
    promptForImage?: string
    _type: 'aiImage'
  }
}

export type TextHeaderSection = {
  _type: 'textHeaderSection'
  title: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  subtitle?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?:
          | 'normal'
          | 'h2'
          | 'h3'
          | 'h4'
          | 'h5'
          | 'h6'
          | 'blockquote'
          | 'small'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<
          | {
              type: 'external' | 'internal'
              href?: string
              reference?: {
                _ref: string
                _type: 'reference'
                _weak?: boolean
                [internalGroqTypeReferenceTo]?: 'page'
              }
              _type: 'link'
              _key: string
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'publication'
            }
          | {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              _key: string
              [internalGroqTypeReferenceTo]?: 'news'
            }
        >
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        altText: string
        promptForImage?: string
        _type: 'imageBlock'
        _key: string
      }
    | {
        buttons?: Array<
          {
            _key: string
          } & Button
        >
        _type: 'buttons'
        _key: string
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        _key: string
        [internalGroqTypeReferenceTo]?: 'testimonial'
      }
  >
}

export type Button = {
  _type: 'button'
  title: string
  type: 'internal' | 'external' | 'functional' | 'file'
  linkExternal?: string
  linkInternal?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'news'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'publication'
      }
  file?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
  functional?: 'contact' | 'subscribe'
}

export type ReducedBody = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote' | 'small'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    type: 'external' | 'internal'
    href?: string
    reference?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'page'
    }
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type Overview = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type Body = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?:
        | 'normal'
        | 'h2'
        | 'h3'
        | 'h4'
        | 'h5'
        | 'h6'
        | 'blockquote'
        | 'small'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<
        | {
            type: 'external' | 'internal'
            href?: string
            reference?: {
              _ref: string
              _type: 'reference'
              _weak?: boolean
              [internalGroqTypeReferenceTo]?: 'page'
            }
            _type: 'link'
            _key: string
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            _key: string
            [internalGroqTypeReferenceTo]?: 'publication'
          }
        | {
            _ref: string
            _type: 'reference'
            _weak?: boolean
            _key: string
            [internalGroqTypeReferenceTo]?: 'news'
          }
      >
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      altText: string
      promptForImage?: string
      _type: 'imageBlock'
      _key: string
    }
  | {
      buttons?: Array<
        {
          _key: string
        } & Button
      >
      _type: 'buttons'
      _key: string
    }
  | {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      _key: string
      [internalGroqTypeReferenceTo]?: 'testimonial'
    }
>

export type LinkCard = {
  _type: 'linkCard'
  title: Overview
  description: Overview
  url?: string
  internalLink?:
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'news'
      }
}

export type AccordionItem = {
  _type: 'accordionItem'
  title: string
  body: ReducedBody
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type Menu = Array<{
  title: string
  isNested?: boolean
  link?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  menuItems?: Array<{
    title: string
    link: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'page'
    }
    _type: 'menuItem'
    _key: string
  }>
  _type: 'menuItem'
  _key: string
}>

export type News = {
  _id: string
  _type: 'news'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  subtitle: string
  body?: Body
  slug: Slug
  image: {
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText: string
    promptForImage?: string
    _type: 'aiImage'
  }
  isInMenu?: boolean
  firstPublishedAt?: string
}

export type Publication = {
  _id: string
  _type: 'publication'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  authors: string
  description: ReducedBody
  pubYear:
    | 2054
    | 2053
    | 2052
    | 2051
    | 2050
    | 2049
    | 2048
    | 2047
    | 2046
    | 2045
    | 2044
    | 2043
    | 2042
    | 2041
    | 2040
    | 2039
    | 2038
    | 2037
    | 2036
    | 2035
    | 2034
    | 2033
    | 2032
    | 2031
    | 2030
    | 2029
    | 2028
    | 2027
    | 2026
    | 2025
    | 2024
    | 2023
    | 2022
    | 2021
    | 2020
    | 2019
    | 2018
    | 2017
    | 2016
    | 2015
    | 2014
    | 2013
    | 2012
    | 2011
    | 2010
    | 2009
    | 2008
    | 2007
    | 2006
    | 2005
    | 2004
    | 2003
    | 2002
    | 2001
    | 2000
    | 1999
    | 1998
    | 1997
    | 1996
    | 1995
    | 1994
    | 1993
    | 1992
    | 1991
    | 1990
    | 1989
    | 1988
    | 1987
    | 1986
    | 1985
    | 1984
    | 1983
    | 1982
    | 1981
    | 1980
    | 1979
    | 1978
    | 1977
    | 1976
    | 1975
  tags?: Array<string>
  url?: string
  file?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.fileAsset'
    }
    _type: 'file'
  }
}

export type Testimonial = {
  _id: string
  _type: 'testimonial'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  body: ReducedBody
  tags?: Array<string>
}

export type DeletedDocsBin = {
  _id: string
  _type: 'deletedDocs.bin'
  _createdAt: string
  _updatedAt: string
  _rev: string
  deletedDocLogs?: Array<{
    docId: string
    deletedAt: string
    type: string
    documentTitle: string
    _type: 'log'
    _key: string
  }>
  deletedDocIds?: Array<string>
  title: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  homePage: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'page'
  }
  menu?: Menu
  quickLinks?: Array<
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'page'
      }
    | {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'news'
      }
  >
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText: string
    promptForImage?: string
    _type: 'aiImage'
  }
  pageNotFound?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText: string
    promptForImage?: string
    _type: 'aiImage'
  }
  serverError?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText: string
    promptForImage?: string
    _type: 'aiImage'
  }
  logos?: {
    logoColor: {
      asset: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      altText: string
      promptForImage?: string
      _type: 'aiImage'
    }
    logoWhite?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      altText: string
      promptForImage?: string
      _type: 'aiImage'
    }
    logoBlack?: {
      asset?: {
        _ref: string
        _type: 'reference'
        _weak?: boolean
        [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
      }
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      altText: string
      promptForImage?: string
      _type: 'aiImage'
    }
  }
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  description: Overview
  image: {
    asset: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    altText: string
    promptForImage?: string
    _type: 'aiImage'
  }
  content: Content
  isInMenu?: boolean
  firstPublishedAt?: string
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type AiImage = {
  _type: 'aiImage'
  asset?: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
  }
  hotspot?: SanityImageHotspot
  crop?: SanityImageCrop
  altText: string
  promptForImage?: string
}

export type MediaTag = {
  _id: string
  _type: 'media.tag'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name?: Slug
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: {
    _ref: string
    _type: 'reference'
    _weak?: boolean
    [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
  }
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type PtString = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type AllSanitySchemaTypes =
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | Geopoint
  | Content
  | NewsSection
  | FurtherLinkSection
  | CtaBannerSection
  | TextSection
  | TestimonialSection
  | AccordionSection
  | ImageHeaderSection
  | TextHeaderSection
  | Button
  | ReducedBody
  | Overview
  | Body
  | LinkCard
  | AccordionItem
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImageAsset
  | SanityImageMetadata
  | Menu
  | News
  | Publication
  | Testimonial
  | DeletedDocsBin
  | SiteSettings
  | Page
  | SanityFileAsset
  | SanityAssetSourceData
  | AiImage
  | MediaTag
  | Slug
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | PtString
export declare const internalGroqTypeReferenceTo: unique symbol
// Source: ./sanity/lib/queries.ts
// Variable: homePageQuery
// Query:   *[_type == "home"][0]{    _id,    overview,    title,  }
export type HomePageQueryResult = null
// Variable: pagesBySlugQuery
// Query:   *[_type == "page" && slug.current == $slug][0] {    _id,    body,    overview,    title,    "slug": slug.current,  }
export type PagesBySlugQueryResult = {
  _id: string
  body: null
  overview: null
  title: string
  slug: string
} | null
// Variable: settingsQuery
// Query:   *[_type == "settings"][0]{    footer,    menuItems[]->{      _type,      "slug": slug.current,      title    },    ogImage,  }
export type SettingsQueryResult = null
// Source: ./sanity/components/inspector/TableOfContents.tsx
// Variable: query
// Query: *[_id == $documentId && _type == 'news'][0]{      body[style != 'normal'] {          _key, _type, style, "text": array::join(children[].text, ' ')        },        _type,        "bodyPath": "body",    }
export type QueryResult = {
  body: Array<
    | {
        _key: string
        _type: 'buttons'
        style: null
        text: null
      }
    | {
        _key: string
        _type: 'imageBlock'
        style: null
        text: null
      }
    | {
        _key: string
        _type: 'reference'
        style: null
        text: null
      }
  > | null
  _type: 'news'
  bodyPath: 'body'
} | null
// Source: ./sanity/schemas/singletons/bin-solution/DeletionLogInputComponent.tsx
// Variable: checkDocumentQuery
// Query: *[_id in $docIds]{              'docId': _id,            }
export type CheckDocumentQueryResult = Array<{
  docId: string
}>
// Source: ./sanity/schemas/singletons/bin-solution/deletedDocBinDocument.tsx
// Variable: getAllDeletedDocIdsUnique
// Query: *[_id == 'deletedDocs.bin']{  "uniqueIds": array::unique(deletedDocIds)}
export type GetAllDeletedDocIdsUniqueResult = Array<
  | {
      uniqueIds: null
    }
  | {
      uniqueIds: Array<string> | null
    }
>
